#!/usr/bin/env python3
"""
This project allows to build a IP prefix to AS map using RPKI as the primary
and IRR as the secondary data source. IRR data is only used if the RPKI data
does not cover the respective IP space.
"""

from kartograf.cli import main

if __name__ == "__main__":
    main()
