name: Build outputs

on:
  push:
    branches: [master]

jobs:
  build-nix-outputs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v3
    - name: Verify Flake Outputs
      run: |
        nix flake check
        nix build .#devShells.x86_64-linux.default
        nix build .#default
